language: python
sudo: required
services:
  - docker
env:
 global:
   - CONAN_UPLOAD: 0
   - CONAN_REFERENCE: "sqlite3/3.14.1"
   - CONAN_USERNAME: "balashovartem"
   - CONAN_CHANNEL: "testing"
   - CONAN_TOTAL_PAGES: 1
   - CONAN_USE_DOCKER: 1
 matrix:
   - CONAN_GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=1

install:
  - pip install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory
script:
  - python build.py
