language: python
sudo: required
services:
  - docker
env:
 global:
   - CONAN_UPLOAD: 0
   - CONAN_REFERENCE: "sqlite3/3.14.1"
   - CONAN_USERNAME: "balashovartem"
   - CONAN_CHANNEL: "testing"
   - CONAN_TOTAL_PAGES: 4
   - CONAN_USE_DOCKER: 1
 matrix:
   - CONAN_GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=1
   - CONAN_GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=2
   - CONAN_GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=3
   - CONAN_GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=4

   - CONAN_GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=1
   - CONAN_GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=2
   - CONAN_GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=3
   - CONAN_GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=4
  
   - CONAN_GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=1
   - CONAN_GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=2
   - CONAN_GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=3
   - CONAN_GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=4
  
   - CONAN_GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=1
   - CONAN_GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=2
   - CONAN_GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=3
   - CONAN_GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=4
  
   - CONAN_GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=1
   - CONAN_GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=2
   - CONAN_GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=3
   - CONAN_GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=4

install:
  - pip install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory
script:
  - python build.py
